### ISSUE TITLE
可以读取中文字体文件中的所有汉字么？

### ISSUE THREAD

**Issue by Dashu-Xu** [JohnWong/PyTTF#1]
如题

**Comment by JohnWong** [comment]
这个是半成品，你看一下一个不错的前端库能不能满足你的需求。https://github.com/ynakajima/ttf.js

**Comment by Dashu-Xu** [comment]
谢了兄弟，忘了回复你，我找到解决方案了，一个叫 `fontTools`的python包可以做这件事情。
